version: '3.7'
services:
  
  ebi01951:
    container_name: app-server
    image: ebi01951:1
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/ebi01951
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database-server:5432/refdb
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        
  db:
    container_name: database-server
    image: ebimpi2test/refdb:latest
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432"]
      interval: 30s
      timeout: 10s
      retries: 5
